<a href="https://colab.research.google.com/github/geligon/geligon/blob/main/AStarMetData_GL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create Environment ‚öì

In [1]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import missingno as msno
import datetime as dt

Read In Data ‚ô•

In [2]:
df=pd.read_csv("MetDataEX.csv")

Overview of Data üëÅ

In [3]:
df.head()

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12549 entries, 0 to 12548
Data columns (total 54 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Object Number            12549 non-null  object
 1   Is Highlight             12549 non-null  bool
 2   Is Timeline Work         12549 non-null  bool
 3   Is Public Domain         12549 non-null  bool
 4   Object ID                12549 non-null  int64
 5   Gallery Number           8559 non-null   object
 6   Department               12549 non-null  object
 7   AccessionYear            12283 non-null  float64
 8   Object Name              12549 non-null  object
 9   Title                    12549 non-null  object
 10  Culture                  10821 non-null  object
 11  Period                   0 non-null      float64
 12  Dynasty                  0 non-null      float64
 13  Reign                    0 non-null      float64
 14  Portfolio                0 non-null      float64
 15  Constituent ID           7095 non-null   float64
 16  Artist Role              7095 non-null   object
 17  Artist Prefix            7095 non-null   object
 18  Artist Display Name      7095 non-null   object
 19  Artist Display Bio       7095 non-null   object
 20  Artist Suffix            7095 non-null   object
 21  Artist Alpha Sort        7095 non-null   object
 22  Artist Nationality       7094 non-null   object
 23  Artist Begin Date        7094 non-null   object
 24  Artist End Date          7094 non-null   object
 25  Artist Gender            921 non-null    object
 26  Artist ULAN URL          5004 non-null   object
 27  Artist Wikidata URL      4785 non-null   object
 28  Object Date              12255 non-null  object
 29  Object Begin Date        12548 non-null  float64
 30  Object End Date          12548 non-null  float64
 31  Medium                   12547 non-null  object
 32  Dimensions               12545 non-null  object
 33  Credit Line              12545 non-null  object
 34  Geography Type           8228 non-null   object
 35  City                     4666 non-null   object
 36  State                    719 non-null    object
 37  County                   720 non-null    object
 38  Country                  8226 non-null   object
 39  Region                   368 non-null    object
 40  Subregion                0 non-null      float64
 41  Locale                   0 non-null      float64
 42  Locus                    0 non-null      float64
 43  Excavation               0 non-null      float64
 44  River                    0 non-null      float64
 45  Classification           4 non-null      object
 46  Rights and Reproduction  73 non-null     object
 47  Link Resource            12548 non-null  object
 48  Object Wikidata URL      1895 non-null   object
 49  Metadata Date            0 non-null      float64
 50  Repository               12548 non-null  object
 51  Tags                     5451 non-null   object
 52  Tags AAT URL             5451 non-null   object
 53  Tags Wikidata URL        5451 non-null   object
dtypes: bool(3), float64(14), int64(1), object(36)
memory usage: 4.9+ MB

~ üïä Drop empty columns and delete any duplicate copy rows that may exist

In [5]:
df = df.dropna(axis=1, how='all')

In [6]:
df_no_duplicates = df.drop_duplicates()

Recheck columns removed

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12549 entries, 0 to 12548
Data columns (total 44 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Object Number            12549 non-null  object
 1   Is Highlight             12549 non-null  bool
 2   Is Timeline Work         12549 non-null  bool
 3   Is Public Domain         12549 non-null  bool
 4   Object ID                12549 non-null  int64
 5   Gallery Number           8559 non-null   object
 6   Department               12549 non-null  object
 7   AccessionYear            12283 non-null  float64
 8   Object Name              12549 non-null  object
 9   Title                    12549 non-null  object
 10  Culture                  10821 non-null  object
 11  Constituent ID           7095 non-null   float64
 12  Artist Role              7095 non-null   object
 13  Artist Prefix            7095 non-null   object
 14  Artist Display Name      7095 non-null   object
 15  Artist Display Bio       7095 non-null   object
 16  Artist Suffix            7095 non-null   object
 17  Artist Alpha Sort        7095 non-null   object
 18  Artist Nationality       7094 non-null   object
 19  Artist Begin Date        7094 non-null   object
 20  Artist End Date          7094 non-null   object
 21  Artist Gender            921 non-null    object
 22  Artist ULAN URL          5004 non-null   object
 23  Artist Wikidata URL      4785 non-null   object
 24  Object Date              12255 non-null  object
 25  Object Begin Date        12548 non-null  float64
 26  Object End Date          12548 non-null  float64
 27  Medium                   12547 non-null  object
 28  Dimensions               12545 non-null  object
 29  Credit Line              12545 non-null  object
 30  Geography Type           8228 non-null   object
 31  City                     4666 non-null   object
 32  State                    719 non-null    object
 33  County                   720 non-null    object
 34  Country                  8226 non-null   object
 35  Region                   368 non-null    object
 36  Classification           4 non-null      object
 37  Rights and Reproduction  73 non-null     object
 38  Link Resource            12548 non-null  object
 39  Object Wikidata URL      1895 non-null   object
 40  Repository               12548 non-null  object
 41  Tags                     5451 non-null   object
 42  Tags AAT URL             5451 non-null   object
 43  Tags Wikidata URL        5451 non-null   object
dtypes: bool(3), float64(4), int64(1), object(36)
memory usage: 4.0+ MB

Add "Unknown" to missing values in "Artist Gender" column

In [8]:
df['Artist Gender'].fillna('Unknown', inplace=True)

<ipython-input-8-6d3a23f54aae>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Artist Gender'].fillna('Unknown', inplace=True)

~ Check for 12549 entries in Gender (though asking for relevance to project might be useful to the end of simplifying)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12549 entries, 0 to 12548
Data columns (total 44 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Object Number            12549 non-null  object
 1   Is Highlight             12549 non-null  bool
 2   Is Timeline Work         12549 non-null  bool
 3   Is Public Domain         12549 non-null  bool
 4   Object ID                12549 non-null  int64
 5   Gallery Number           8559 non-null   object
 6   Department               12549 non-null  object
 7   AccessionYear            12283 non-null  float64
 8   Object Name              12549 non-null  object
 9   Title                    12549 non-null  object
 10  Culture                  10821 non-null  object
 11  Constituent ID           7095 non-null   float64
 12  Artist Role              7095 non-null   object
 13  Artist Prefix            7095 non-null   object
 14  Artist Display Name      7095 non-null   object
 15  Artist Display Bio       7095 non-null   object
 16  Artist Suffix            7095 non-null   object
 17  Artist Alpha Sort        7095 non-null   object
 18  Artist Nationality       7094 non-null   object
 19  Artist Begin Date        7094 non-null   object
 20  Artist End Date          7094 non-null   object
 21  Artist Gender            12549 non-null  object
 22  Artist ULAN URL          5004 non-null   object
 23  Artist Wikidata URL      4785 non-null   object
 24  Object Date              12255 non-null  object
 25  Object Begin Date        12548 non-null  float64
 26  Object End Date          12548 non-null  float64
 27  Medium                   12547 non-null  object
 28  Dimensions               12545 non-null  object
 29  Credit Line              12545 non-null  object
 30  Geography Type           8228 non-null   object
 31  City                     4666 non-null   object
 32  State                    719 non-null    object
 33  County                   720 non-null    object
 34  Country                  8226 non-null   object
 35  Region                   368 non-null    object
 36  Classification           4 non-null      object
 37  Rights and Reproduction  73 non-null     object
 38  Link Resource            12548 non-null  object
 39  Object Wikidata URL      1895 non-null   object
 40  Repository               12548 non-null  object
 41  Tags                     5451 non-null   object
 42  Tags AAT URL             5451 non-null   object
 43  Tags Wikidata URL        5451 non-null   object
dtypes: bool(3), float64(4), int64(1), object(36)
memory usage: 4.0+ MB

Review the Data Types re: Uniformity

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12549 entries, 0 to 12548
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Object ID            12549 non-null  int64
 1   Accession Year       12549 non-null  int64
 2   Artist Alpha Sort    12549 non-null  object
 3   Artist Begin Date    5844 non-null   float64
 4   Artist Display Bio   12549 non-null  object
 5   Artist Display Name  12549 non-null  object
 6   Artist End Date      5742 non-null   float64
 7   Artist Gender        12549 non-null  object
 8   Artist Nationality   12549 non-null  object
 9   Artist Prefix        12549 non-null  object
 10  Artist Role          12549 non-null  object
 11  Artist Suffix        12549 non-null  object
 12  Artist ULAN URL      12549 non-null  object
 13  Artist Wikidata URL  12549 non-null  object
 14  City                 12549 non-null  object
 15  Constituent ID       7095 non-null   float64
 16  Country              12549 non-null  object
 17  Credit Line          12549 non-null  object
 18  Culture              12549 non-null  object
 19  Department           12549 non-null  object
 20  Dimensions           12549 non-null  object
 21  Gallery Number       12549 non-null  object
 22  Geography Type       12549 non-null  object
 23  Is Highlight         12549 non-null  bool
 24  Is Public Domain     12549 non-null  bool
 25  Is Timeline Work     12549 non-null  bool
 26  Link Resource        12549 non-null  object
 27  Medium               12549 non-null  object
 28  Object Begin Date    12548 non-null  float64
 29  Object Date          1867 non-null   float64
 30  Object End Date      12548 non-null  float64
 31  Object Name          12549 non-null  object
 32  Object Number        12549 non-null  object
 33  Object Wikidata URL  12549 non-null  object
 34  Repository           12549 non-null  object
 35  State                12549 non-null  object
 36  Tags                 12549 non-null  object
 37  Tags AAT URL         12549 non-null  object
 38  Tags Wikidata URL    12549 non-null  object
 39  Title                12549 non-null  object
dtypes: bool(3), float64(6), int64(2), object(29)
memory usage: 3.6+ MB

Change Heading to "Accession Year"

In [11]:
df.rename(columns={'AccessionYear': 'Accession Year'}, inplace=True)
df.head()

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,Accession Year,Object Name,Title,...,Country,Region,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

Address Accession Year Dates

In [12]:
df

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,Accession Year,Object Name,Title,...,Country,Region,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12544,66.165.9,False,False,False,13714,NaN,The American Wing,1966.0,Handkerchief,Handkerchief,...,United States,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
12545,36.89.1,False,False,True,13715,NaN,The American Wing,1936.0,Piece,Piece,...,France,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,"Metropolitan Museum of Art, New York, NY",Swans|Deer|Elephants|Human Figures,http://vocab.getty.edu/page/aat/300250103|http...,https://www.wikidata.org/wiki/Q34384|https://w...
12546,36.89.2,False,False,True,13716,NaN,The American Wing,1936.0,Piece,Piece,...,France,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,"Metropolitan Museum of Art, New York, NY",Birds|Children|Horses|Human Figures,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...
12547,1985.40.1,False,False,False,13717,NaN,The American Wing,1985.0,Length,Length,...,United States,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
12548,66.165.4,False,False,False,13718,NaN,The American Wing,1966.0,Length,Length,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df['Accession Year'] = df['Accession Year'].fillna(-1).astype(int)

Check if changed to int

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12549 entries, 0 to 12548
Data columns (total 44 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Object Number            12549 non-null  object
 1   Is Highlight             12549 non-null  bool
 2   Is Timeline Work         12549 non-null  bool
 3   Is Public Domain         12549 non-null  bool
 4   Object ID                12549 non-null  int64
 5   Gallery Number           8559 non-null   object
 6   Department               12549 non-null  object
 7   Accession Year           12549 non-null  int64
 8   Object Name              12549 non-null  object
 9   Title                    12549 non-null  object
 10  Culture                  10821 non-null  object
 11  Constituent ID           7095 non-null   float64
 12  Artist Role              7095 non-null   object
 13  Artist Prefix            7095 non-null   object
 14  Artist Display Name      7095 non-null   object
 15  Artist Display Bio       7095 non-null   object
 16  Artist Suffix            7095 non-null   object
 17  Artist Alpha Sort        7095 non-null   object
 18  Artist Nationality       7094 non-null   object
 19  Artist Begin Date        7094 non-null   object
 20  Artist End Date          7094 non-null   object
 21  Artist Gender            12549 non-null  object
 22  Artist ULAN URL          5004 non-null   object
 23  Artist Wikidata URL      4785 non-null   object
 24  Object Date              12255 non-null  object
 25  Object Begin Date        12548 non-null  float64
 26  Object End Date          12548 non-null  float64
 27  Medium                   12547 non-null  object
 28  Dimensions               12545 non-null  object
 29  Credit Line              12545 non-null  object
 30  Geography Type           8228 non-null   object
 31  City                     4666 non-null   object
 32  State                    719 non-null    object
 33  County                   720 non-null    object
 34  Country                  8226 non-null   object
 35  Region                   368 non-null    object
 36  Classification           4 non-null      object
 37  Rights and Reproduction  73 non-null     object
 38  Link Resource            12548 non-null  object
 39  Object Wikidata URL      1895 non-null   object
 40  Repository               12548 non-null  object
 41  Tags                     5451 non-null   object
 42  Tags AAT URL             5451 non-null   object
 43  Tags Wikidata URL        5451 non-null   object
dtypes: bool(3), float64(3), int64(2), object(36)
memory usage: 4.0+ MB

~ üëÄ Check Number of Missing Values

In [15]:
df.isna().sum()

Object Number                  0
Is Highlight                   0
Is Timeline Work               0
Is Public Domain               0
Object ID                      0
Gallery Number              3990
Department                     0
Accession Year                 0
Object Name                    0
Title                          0
Culture                     1728
Constituent ID              5454
Artist Role                 5454
Artist Prefix               5454
Artist Display Name         5454
Artist Display Bio          5454
Artist Suffix               5454
Artist Alpha Sort           5454
Artist Nationality          5455
Artist Begin Date           5455
Artist End Date             5455
Artist Gender                  0
Artist ULAN URL             7545
Artist Wikidata URL         7764
Object Date                  294
Object Begin Date              1
Object End Date                1
Medium                         2
Dimensions                     4
Credit Line                    4
Geography Type              4321
City                        7883
State                      11830
County                     11829
Country                     4323
Region                     12181
Classification             12545
Rights and Reproduction    12476
Link Resource                  1
Object Wikidata URL        10654
Repository                     1
Tags                        7098
Tags AAT URL                7098
Tags Wikidata URL           7098
dtype: int64

~ Drop Columns with too many missing entries to be useful or that clearly contain incorrect information. In this case, entires in County and Region appear to be repeated for both columns and these are clearly connected - possibly an entry error

In [16]:
to_drop = ['County',
'Region',
'Classification',
'Rights and Reproduction']
df.drop(to_drop, inplace = True, axis = 1)

~ Check what Columns I have left

In [17]:
print(df.columns)

Index(['Object Number', 'Is Highlight', 'Is Timeline Work', 'Is Public Domain',
       'Object ID', 'Gallery Number', 'Department', 'Accession Year',
       'Object Name', 'Title', 'Culture', 'Constituent ID', 'Artist Role',
       'Artist Prefix', 'Artist Display Name', 'Artist Display Bio',
       'Artist Suffix', 'Artist Alpha Sort', 'Artist Nationality',
       'Artist Begin Date', 'Artist End Date', 'Artist Gender',
       'Artist ULAN URL', 'Artist Wikidata URL', 'Object Date',
       'Object Begin Date', 'Object End Date', 'Medium', 'Dimensions',
       'Credit Line', 'Geography Type', 'City', 'State', 'Country',
       'Link Resource', 'Object Wikidata URL', 'Repository', 'Tags',
       'Tags AAT URL', 'Tags Wikidata URL'],
      dtype='object')

In [18]:
df.head()

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,Accession Year,Object Name,Title,...,Geography Type,City,State,Country,Link Resource,Object Wikidata URL,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [19]:
df.isna().sum()

Object Number              0
Is Highlight               0
Is Timeline Work           0
Is Public Domain           0
Object ID                  0
Gallery Number          3990
Department                 0
Accession Year             0
Object Name                0
Title                      0
Culture                 1728
Constituent ID          5454
Artist Role             5454
Artist Prefix           5454
Artist Display Name     5454
Artist Display Bio      5454
Artist Suffix           5454
Artist Alpha Sort       5454
Artist Nationality      5455
Artist Begin Date       5455
Artist End Date         5455
Artist Gender              0
Artist ULAN URL         7545
Artist Wikidata URL     7764
Object Date              294
Object Begin Date          1
Object End Date            1
Medium                     2
Dimensions                 4
Credit Line                4
Geography Type          4321
City                    7883
State                  11830
Country                 4323
Link Resource              1
Object Wikidata URL    10654
Repository                 1
Tags                    7098
Tags AAT URL            7098
Tags Wikidata URL       7098
dtype: int64

üçé Check on Data Overview

In [20]:
df

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,Accession Year,Object Name,Title,...,Geography Type,City,State,Country,Link Resource,Object Wikidata URL,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12544,66.165.9,False,False,False,13714,NaN,The American Wing,1966,Handkerchief,Handkerchief,...,(none assigned),New Lebanon,NaN,United States,http://www.metmuseum.org/art/collection/search...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
12545,36.89.1,False,False,True,13715,NaN,The American Wing,1936,Piece,Piece,...,Made in,NaN,NaN,France,http://www.metmuseum.org/art/collection/search...,NaN,"Metropolitan Museum of Art, New York, NY",Swans|Deer|Elephants|Human Figures,http://vocab.getty.edu/page/aat/300250103|http...,https://www.wikidata.org/wiki/Q34384|https://w...
12546,36.89.2,False,False,True,13716,NaN,The American Wing,1936,Piece,Piece,...,Made in,NaN,NaN,France,http://www.metmuseum.org/art/collection/search...,NaN,"Metropolitan Museum of Art, New York, NY",Birds|Children|Horses|Human Figures,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...
12547,1985.40.1,False,False,False,13717,NaN,The American Wing,1985,Length,Length,...,Made in,New Lebanon,NaN,United States,http://www.metmuseum.org/art/collection/search...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
12548,66.165.4,False,False,False,13718,NaN,The American Wing,1966,Length,Length,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Sort Columns ABC

In [21]:
sorted_columns = sorted(df.columns)
df = df.reindex(columns=sorted_columns)
df.head()

,Accession Year,Artist Alpha Sort,Artist Begin Date,Artist Display Bio,Artist Display Name,Artist End Date,Artist Gender,Artist Nationality,Artist Prefix,Artist Role,...,Object ID,Object Name,Object Number,Object Wikidata URL,Repository,State,Tags,Tags AAT URL,Tags Wikidata URL,Title
0,1979,"Longacre, James Barton",1794,"American, Delaware County, Pennsylvania 1794‚Äì1...",James Barton Longacre,1869,Unknown,American,,Maker,...,1,Coin,1979.486.1,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,One-dollar Liberty Head Coin
1,1980,"Gobrecht, Christian",1785,1785‚Äì1844,Christian Gobrecht,1844,Unknown,,,Maker,...,2,Coin,1980.264.5,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Ten-dollar Liberty Head Coin
2,1967,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,...,3,Coin,67.265.9,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Two-and-a-Half Dollar Coin
3,1967,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,...,4,Coin,67.265.10,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Two-and-a-Half Dollar Coin
4,1967,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,...,5,Coin,67.265.11,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Two-and-a-Half Dollar Coin

Move Object ID to First Column

In [22]:
columns = df.columns.tolist()

In [23]:
cols = list(df.columns)

In [24]:
cols.insert(0, cols.pop(cols.index('Object ID')))

In [25]:
df = df[cols]

In [26]:
df

,Object ID,Accession Year,Artist Alpha Sort,Artist Begin Date,Artist Display Bio,Artist Display Name,Artist End Date,Artist Gender,Artist Nationality,Artist Prefix,...,Object End Date,Object Name,Object Number,Object Wikidata URL,Repository,State,Tags,Tags AAT URL,Tags Wikidata URL,Title
0,1,1979,"Longacre, James Barton",1794,"American, Delaware County, Pennsylvania 1794‚Äì1...",James Barton Longacre,1869,Unknown,American,,...,1853.0,Coin,1979.486.1,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,One-dollar Liberty Head Coin
1,2,1980,"Gobrecht, Christian",1785,1785‚Äì1844,Christian Gobrecht,1844,Unknown,,,...,1901.0,Coin,1980.264.5,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Ten-dollar Liberty Head Coin
2,3,1967,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,...,1927.0,Coin,67.265.9,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Two-and-a-Half Dollar Coin
3,4,1967,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,...,1927.0,Coin,67.265.10,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Two-and-a-Half Dollar Coin
4,5,1967,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,...,1927.0,Coin,67.265.11,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Two-and-a-Half Dollar Coin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12544,13714,1966,United Society of Believers in Christ‚Äôs Second...,1750,"American, active ca. 1750‚Äìpresent",United Society of Believers in Christ‚Äôs Second...,9999,Unknown,,,...,1900.0,Handkerchief,66.165.9,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Handkerchief
12545,13715,1936,"Huet, Jean-Baptiste, I",1745,"French, Paris 1745‚Äì1811 Paris",Jean-Baptiste Huet I,1811,Unknown,French,,...,1788.0,Piece,36.89.1,NaN,"Metropolitan Museum of Art, New York, NY",NaN,Swans|Deer|Elephants|Human Figures,http://vocab.getty.edu/page/aat/300250103|http...,https://www.wikidata.org/wiki/Q34384|https://w...,Piece
12546,13716,1936,"Huet, Jean-Baptiste, I",1745,"French, Paris 1745‚Äì1811 Paris",Jean-Baptiste Huet I,1811,Unknown,French,,...,1788.0,Piece,36.89.2,NaN,"Metropolitan Museum of Art, New York, NY",NaN,Birds|Children|Horses|Human Figures,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...,Piece
12547,13717,1985,United Society of Believers in Christ‚Äôs Second...,1750,"American, active ca. 1750‚Äìpresent",United Society of Believers in Christ‚Äôs Second...,9999,Unknown,,,...,1900.0,Length,1985.40.1,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,Length
12548,13718,1966,"Jacobs, Clarissa|North Family |United Society ...",NaN,"| |American, active ca. 1750‚Äìpresent",Clarissa Jacobs|North Family|United Society of...,NaN,Unknown,NaN,| |,...,NaN,Length,66.165.4,NaN,NaN,NaN,NaN,NaN,NaN,Length

(Above shows that ID numbers for the museum have not all been accounted for, assuming they started at 1 and went up sequentially. This may be useful in assessing how complete their inventory process has been thus far and/or examining loss of pieces?)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12549 entries, 0 to 12548
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Object ID            12549 non-null  int64
 1   Accession Year       12549 non-null  int64
 2   Artist Alpha Sort    7095 non-null   object
 3   Artist Begin Date    7094 non-null   object
 4   Artist Display Bio   7095 non-null   object
 5   Artist Display Name  7095 non-null   object
 6   Artist End Date      7094 non-null   object
 7   Artist Gender        12549 non-null  object
 8   Artist Nationality   7094 non-null   object
 9   Artist Prefix        7095 non-null   object
 10  Artist Role          7095 non-null   object
 11  Artist Suffix        7095 non-null   object
 12  Artist ULAN URL      5004 non-null   object
 13  Artist Wikidata URL  4785 non-null   object
 14  City                 4666 non-null   object
 15  Constituent ID       7095 non-null   float64
 16  Country              8226 non-null   object
 17  Credit Line          12545 non-null  object
 18  Culture              10821 non-null  object
 19  Department           12549 non-null  object
 20  Dimensions           12545 non-null  object
 21  Gallery Number       8559 non-null   object
 22  Geography Type       8228 non-null   object
 23  Is Highlight         12549 non-null  bool
 24  Is Public Domain     12549 non-null  bool
 25  Is Timeline Work     12549 non-null  bool
 26  Link Resource        12548 non-null  object
 27  Medium               12547 non-null  object
 28  Object Begin Date    12548 non-null  float64
 29  Object Date          12255 non-null  object
 30  Object End Date      12548 non-null  float64
 31  Object Name          12549 non-null  object
 32  Object Number        12549 non-null  object
 33  Object Wikidata URL  1895 non-null   object
 34  Repository           12548 non-null  object
 35  State                719 non-null    object
 36  Tags                 5451 non-null   object
 37  Tags AAT URL         5451 non-null   object
 38  Tags Wikidata URL    5451 non-null   object
 39  Title                12549 non-null  object
dtypes: bool(3), float64(3), int64(2), object(32)
memory usage: 3.6+ MB

Clean Date Formats

In [40]:
date_columns = ['Artist Begin Date', 'Artist End Date', 'Object End Date','Object Date']

for col in date_columns:
    # Convert to datetime
    df[col] = pd.to_datetime(df[col], errors='coerce')

    # Extract year and replace the original column
    df[col] = df[col].dt.year

    # Convert to integer while handling NaN values
    df[col] = df[col].astype('Int64')

In [41]:
df.head()

,Object ID,Accession Year,Artist Alpha Sort,Artist Begin Date,Artist Display Bio,Artist Display Name,Artist End Date,Artist Gender,Artist Nationality,Artist Prefix,...,Object End Date,Object Name,Object Number,Object Wikidata URL,Repository,State,Tags,Tags AAT URL,Tags Wikidata URL,Title
0,1,1979,"Longacre, James Barton",1970,"American, Delaware County, Pennsylvania 1794‚Äì1...",James Barton Longacre,1970,Unknown,American,Unknown,...,1970,Coin,1979.486.1,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,One-dollar Liberty Head Coin
1,2,1980,"Gobrecht, Christian",1970,1785‚Äì1844,Christian Gobrecht,1970,Unknown,Unknown,Unknown,...,1970,Coin,1980.264.5,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Ten-dollar Liberty Head Coin
2,3,1967,Unknown,<NA>,Unknown,Unknown,<NA>,Unknown,Unknown,Unknown,...,1970,Coin,67.265.9,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Two-and-a-Half Dollar Coin
3,4,1967,Unknown,<NA>,Unknown,Unknown,<NA>,Unknown,Unknown,Unknown,...,1970,Coin,67.265.10,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Two-and-a-Half Dollar Coin
4,5,1967,Unknown,<NA>,Unknown,Unknown,<NA>,Unknown,Unknown,Unknown,...,1970,Coin,67.265.11,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Two-and-a-Half Dollar Coin

Strip Whitespace

In [42]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12549 entries, 0 to 12548
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Object ID            12549 non-null  int64
 1   Accession Year       12549 non-null  int64
 2   Artist Alpha Sort    12549 non-null  object
 3   Artist Begin Date    5844 non-null   Int64
 4   Artist Display Bio   12549 non-null  object
 5   Artist Display Name  12549 non-null  object
 6   Artist End Date      5742 non-null   Int64
 7   Artist Gender        12549 non-null  object
 8   Artist Nationality   12549 non-null  object
 9   Artist Prefix        12549 non-null  object
 10  Artist Role          12549 non-null  object
 11  Artist Suffix        12549 non-null  object
 12  Artist ULAN URL      12549 non-null  object
 13  Artist Wikidata URL  12549 non-null  object
 14  City                 12549 non-null  object
 15  Constituent ID       7095 non-null   float64
 16  Country              12549 non-null  object
 17  Credit Line          12549 non-null  object
 18  Culture              12549 non-null  object
 19  Department           12549 non-null  object
 20  Dimensions           12549 non-null  object
 21  Gallery Number       12549 non-null  object
 22  Geography Type       12549 non-null  object
 23  Is Highlight         12549 non-null  bool
 24  Is Public Domain     12549 non-null  bool
 25  Is Timeline Work     12549 non-null  bool
 26  Link Resource        12549 non-null  object
 27  Medium               12549 non-null  object
 28  Object Begin Date    12548 non-null  float64
 29  Object Date          1867 non-null   Int64
 30  Object End Date      12548 non-null  Int64
 31  Object Name          12549 non-null  object
 32  Object Number        12549 non-null  object
 33  Object Wikidata URL  12549 non-null  object
 34  Repository           12549 non-null  object
 35  State                12549 non-null  object
 36  Tags                 12549 non-null  object
 37  Tags AAT URL         12549 non-null  object
 38  Tags Wikidata URL    12549 non-null  object
 39  Title                12549 non-null  object
dtypes: Int64(4), bool(3), float64(2), int64(2), object(29)
memory usage: 3.6+ MB

In [32]:
# Function to remove blank space entries
def remove_blank_spaces(x):
    if isinstance(x, str):
        return x.strip() if x.strip() else pd.NA
    return x

# Apply the function to all elements in the DataFrame
df = df.map(remove_blank_spaces)

# Remove any rows that are now entirely NA
df = df.dropna(how='all')

# Reset the index if needed
df = df.reset_index(drop=True)

In [33]:
object_columns = df.select_dtypes(include=['object']).columns

for column in object_columns:
    df[column] = df[column].fillna('Unknown')

In [34]:
df

,Object ID,Accession Year,Artist Alpha Sort,Artist Begin Date,Artist Display Bio,Artist Display Name,Artist End Date,Artist Gender,Artist Nationality,Artist Prefix,...,Object End Date,Object Name,Object Number,Object Wikidata URL,Repository,State,Tags,Tags AAT URL,Tags Wikidata URL,Title
0,1,1979,"Longacre, James Barton",1794.0,"American, Delaware County, Pennsylvania 1794‚Äì1...",James Barton Longacre,1869.0,Unknown,American,Unknown,...,1970.0,Coin,1979.486.1,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,One-dollar Liberty Head Coin
1,2,1980,"Gobrecht, Christian",1785.0,1785‚Äì1844,Christian Gobrecht,1844.0,Unknown,Unknown,Unknown,...,1970.0,Coin,1980.264.5,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Ten-dollar Liberty Head Coin
2,3,1967,Unknown,NaN,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,...,1970.0,Coin,67.265.9,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Two-and-a-Half Dollar Coin
3,4,1967,Unknown,NaN,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,...,1970.0,Coin,67.265.10,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Two-and-a-Half Dollar Coin
4,5,1967,Unknown,NaN,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,...,1970.0,Coin,67.265.11,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Two-and-a-Half Dollar Coin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12544,13714,1966,United Society of Believers in Christ‚Äôs Second...,1750.0,"American, active ca. 1750‚Äìpresent",United Society of Believers in Christ‚Äôs Second...,NaN,Unknown,Unknown,Unknown,...,1970.0,Handkerchief,66.165.9,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Handkerchief
12545,13715,1936,"Huet, Jean-Baptiste, I",1745.0,"French, Paris 1745‚Äì1811 Paris",Jean-Baptiste Huet I,1811.0,Unknown,French,Unknown,...,1970.0,Piece,36.89.1,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Swans|Deer|Elephants|Human Figures,http://vocab.getty.edu/page/aat/300250103|http...,https://www.wikidata.org/wiki/Q34384|https://w...,Piece
12546,13716,1936,"Huet, Jean-Baptiste, I",1745.0,"French, Paris 1745‚Äì1811 Paris",Jean-Baptiste Huet I,1811.0,Unknown,French,Unknown,...,1970.0,Piece,36.89.2,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Birds|Children|Horses|Human Figures,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...,Piece
12547,13717,1985,United Society of Believers in Christ‚Äôs Second...,1750.0,"American, active ca. 1750‚Äìpresent",United Society of Believers in Christ‚Äôs Second...,NaN,Unknown,Unknown,Unknown,...,1970.0,Length,1985.40.1,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Length
12548,13718,1966,"Jacobs, Clarissa|North Family |United Society ...",NaN,"| |American, active ca. 1750‚Äìpresent",Clarissa Jacobs|North Family|United Society of...,NaN,Unknown,Unknown,| |,...,NaN,Length,66.165.4,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Length

Replace NaN with "Unknown"

In [35]:
df

,Object ID,Accession Year,Artist Alpha Sort,Artist Begin Date,Artist Display Bio,Artist Display Name,Artist End Date,Artist Gender,Artist Nationality,Artist Prefix,...,Object End Date,Object Name,Object Number,Object Wikidata URL,Repository,State,Tags,Tags AAT URL,Tags Wikidata URL,Title
0,1,1979,"Longacre, James Barton",1794.0,"American, Delaware County, Pennsylvania 1794‚Äì1...",James Barton Longacre,1869.0,Unknown,American,Unknown,...,1970.0,Coin,1979.486.1,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,One-dollar Liberty Head Coin
1,2,1980,"Gobrecht, Christian",1785.0,1785‚Äì1844,Christian Gobrecht,1844.0,Unknown,Unknown,Unknown,...,1970.0,Coin,1980.264.5,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Ten-dollar Liberty Head Coin
2,3,1967,Unknown,NaN,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,...,1970.0,Coin,67.265.9,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Two-and-a-Half Dollar Coin
3,4,1967,Unknown,NaN,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,...,1970.0,Coin,67.265.10,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Two-and-a-Half Dollar Coin
4,5,1967,Unknown,NaN,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,...,1970.0,Coin,67.265.11,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Two-and-a-Half Dollar Coin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12544,13714,1966,United Society of Believers in Christ‚Äôs Second...,1750.0,"American, active ca. 1750‚Äìpresent",United Society of Believers in Christ‚Äôs Second...,NaN,Unknown,Unknown,Unknown,...,1970.0,Handkerchief,66.165.9,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Handkerchief
12545,13715,1936,"Huet, Jean-Baptiste, I",1745.0,"French, Paris 1745‚Äì1811 Paris",Jean-Baptiste Huet I,1811.0,Unknown,French,Unknown,...,1970.0,Piece,36.89.1,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Swans|Deer|Elephants|Human Figures,http://vocab.getty.edu/page/aat/300250103|http...,https://www.wikidata.org/wiki/Q34384|https://w...,Piece
12546,13716,1936,"Huet, Jean-Baptiste, I",1745.0,"French, Paris 1745‚Äì1811 Paris",Jean-Baptiste Huet I,1811.0,Unknown,French,Unknown,...,1970.0,Piece,36.89.2,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Birds|Children|Horses|Human Figures,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...,Piece
12547,13717,1985,United Society of Believers in Christ‚Äôs Second...,1750.0,"American, active ca. 1750‚Äìpresent",United Society of Believers in Christ‚Äôs Second...,NaN,Unknown,Unknown,Unknown,...,1970.0,Length,1985.40.1,Unknown,"Metropolitan Museum of Art, New York, NY",Unknown,Unknown,Unknown,Unknown,Length
12548,13718,1966,"Jacobs, Clarissa|North Family |United Society ...",NaN,"| |American, active ca. 1750‚Äìpresent",Clarissa Jacobs|North Family|United Society of...,NaN,Unknown,Unknown,| |,...,NaN,Length,66.165.4,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Length

In [36]:
df.dtypes

Object ID                int64
Accession Year           int64
Artist Alpha Sort       object
Artist Begin Date      float64
Artist Display Bio      object
Artist Display Name     object
Artist End Date        float64
Artist Gender           object
Artist Nationality      object
Artist Prefix           object
Artist Role             object
Artist Suffix           object
Artist ULAN URL         object
Artist Wikidata URL     object
City                    object
Constituent ID         float64
Country                 object
Credit Line             object
Culture                 object
Department              object
Dimensions              object
Gallery Number          object
Geography Type          object
Is Highlight              bool
Is Public Domain          bool
Is Timeline Work          bool
Link Resource           object
Medium                  object
Object Begin Date      float64
Object Date            float64
Object End Date        float64
Object Name             object
Object Number           object
Object Wikidata URL     object
Repository              object
State                   object
Tags                    object
Tags AAT URL            object
Tags Wikidata URL       object
Title                   object
dtype: object

In [37]:
df.describe()

,Object ID,Accession Year,Artist Begin Date,Artist End Date,Constituent ID,Object Begin Date,Object Date,Object End Date
count,12549.000000,12549.000000,5844.000000,5742.000000,7.095000e+03,12548.000000,1867.000000,12548.0
mean,6772.089808,1901.652642,1816.916324,1877.381574,1.682482e+17,1822.050765,1862.569363,1970.0
std,3939.600059,281.239958,46.873479,51.623705,1.415345e+19,63.418491,43.815198,0.0
min,1.000000,-1.000000,1678.000000,1681.000000,1.070000e+02,0.000000,1679.000000,1970.0
25%,3357.000000,1922.000000,1785.000000,1844.000000,1.480000e+02,1787.000000,1840.500000,1970.0
50%,6678.000000,1946.000000,1826.000000,1888.000000,2.990000e+02,1828.000000,1872.000000,1970.0
75%,10154.000000,1965.000000,1856.000000,1922.000000,1.625300e+04,1870.000000,1893.000000,1970.0
max,13718.000000,2021.000000,1918.000000,2063.000000,1.192170e+21,1976.000000,1976.000000,1970.0

In [38]:
df.isna().sum()

Object ID                  0
Accession Year             0
Artist Alpha Sort          0
Artist Begin Date       6705
Artist Display Bio         0
Artist Display Name        0
Artist End Date         6807
Artist Gender              0
Artist Nationality         0
Artist Prefix              0
Artist Role                0
Artist Suffix              0
Artist ULAN URL            0
Artist Wikidata URL        0
City                       0
Constituent ID          5454
Country                    0
Credit Line                0
Culture                    0
Department                 0
Dimensions                 0
Gallery Number             0
Geography Type             0
Is Highlight               0
Is Public Domain           0
Is Timeline Work           0
Link Resource              0
Medium                     0
Object Begin Date          1
Object Date            10682
Object End Date            1
Object Name                0
Object Number              0
Object Wikidata URL        0
Repository                 0
State                      0
Tags                       0
Tags AAT URL               0
Tags Wikidata URL          0
Title                      0
dtype: int64